version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      # Run python script
      - run: pip install PyGithub --user
      - run: python3 main.py
      - run: git version
      - run: git status
      - run: git config --global user.email "aikuyun.tsl@gmail.com"
      - run: git config --global user.name "aikuyun"
      - run: git checkout master
      - run: git add .
      - run: git commit -m "Update From Circle CI"
      - run: git push https://$GITHUB_LOGIN:$GITHUB_PASSWORD@github.com/$GITHUB_LOGIN/bb_everyday.git
      - run: echo 'done'
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "05 11 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build
